twig:
    default_path: '%kernel.project_dir%/templates'
    # L'option form_theme vous permet de renseigner un layout général
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
